### ISSUE TITLE
Pet Images

### ISSUE THREAD

**Issue by JohannMerck** [Inelukas/pet-app#18]
User Story

Value Proposition

As a user
I want to have a consistent and visually appealing experience across all pages,
in order to be able to focus on the gameplay aspects of the game.

Description

Replace all existing small emoticons of pets in the PetList, PetDetails, PetCreate, and Garden Page with pet images.
Ensure all pet images are in the same drawing style. Ensure that all pet images are properly centered within their containers, regardless of screen size or orientation.

Acceptance Criteria

- [ ] All visual representations of Pets are displayed as consistent images.
- [ ] Image placement: Pet images must be added to the appropriate sections and be displayed clearly without distortion.
- [ ] Image centering: All pet images should be perfectly centered within their containers, with appropriate padding or margins.
- [ ] Responsive behavior: The layout should remain consistent and visually appealing on different screen sizes and orientations.

Tasks

 - [ ] create feature brach pet-images
 - [ ] Replace small pet emoticons with corresponding pet images on the PetList Page/PetDetails Page/PetCreate Page.
 - [ ] Ensure all images follow the same drawing style and visual guidelines.
 - [ ] Adjust the CSS to ensure images are centered in their containers.

**Comment by LorenzCoachK** [comment]
It´s clear (at least to me) what the US is about. I think I would repeat the topic about "for whom is which part of the US", when I suggest to replace some technical expressions like "container, section, padding or margin" in the acceptance criteria.

No big deal, so green hook.
Best
Lorenz
