### ISSUE TITLE
Tapping Game

### ISSUE THREAD

**Issue by JohannMerck** [Inelukas/pet-app#27]
User Story

Value Proposition

As a player, i want to play a game that includes tapping on buttons that light up randomly,
In order challenge my reflexed and gain points which will increase the energy level of my Pet. 

Description

![Image](https://github.com/user-attachments/assets/d01a9c8d-7eec-41f5-841b-994909befafb)

The game consists of several buttons on the screen. Buttons light up randomly, and the player needs to tap them as quickly as possible to score points. Each correct tap earns the player points, while tapping the wrong buttons result in point deduction. The game speeds up every 10 seconds, increasing the challenge. The score increases or decreases the Energy Level of the current Pet in real time. 

Acceptance Criteria

- [ ] interactive, working and intuitive user interface including all necessary buttons and components
- [ ] one ore more buttons light up for a short duration. If tapped within this time, it registers as a hit and adds one point. If not, it fades out, and no points are given.
- [ ] If the player taps the wrong button, he is deducted one point. 
- [ ] Gaining Points increases the Energy level of the current pet. 
- [ ] a dynamic bar indicates the energy level of the current Pet. 
- [ ] implement reset button, which sets the score back to 0 and resets the game. 
- [ ] implement start and pause button, which can be toggled to start and pause the game. 
- [ ] every 10 seconds, the speed gradually increases. 
- [ ] implement 60s timer. When the timer runs out, the game resets and a message is displayed. 

Tasks
- [ ] Create feature branch tapping-game
- [ ] Design and integrate the user interface with all necessary buttons and score display.
- [ ] Develop the random button lighting functionality. 
- [ ] Implement the tap detection logic for correct and incorrect taps.
- [ ] Implement highscore functionality. 
- [ ] implement dynamic energy level indicator 
- [ ] implement function that increases game every 10 seconds
- [ ] implement message indicating that the speed level has increased
- [ ] implement reset button, which resets the score and restarts the game.
- [ ] implement timer and timer message

**Comment by SylvieDoumet** [comment]
Your user story effectively conveys the value proposition and desired feature but could benefit from more detail about the player experience (such as how the game should feel and the role of effects in enhancing that experience) and the pet's role. 

The criteria cover the core functionality but are somewhat a bit flue, disjointed and could be better organized. 

The User story (once more!) lacks specifics about how the game handles edge cases or unexpected behavior
