### ISSUE TITLE
Characteristics/Stat Update

### ISSUE THREAD

**Issue by Inelukas** [Inelukas/pet-app#48]
Value Proposition

As a user,
I want each of my pets' unique characteristics to impact their stats in more diverse and balanced ways,
So that I can enjoy richer, more personalized gameplay experiences with each pet.

Description

Each characteristic will have both positive and negative effects on pet stats to create a more strategic and engaging experience. Some effects will directly influence the pet's gameplay stats, while others will be purely visual, adding depth and variety to the pet simulation.
The intelligence stat will directly influence the three stats hunger, energy and happiness

Acceptance Criteria

- [x] The in-/decrease of hunger, happiness and energy depends on the intelligence stat: the higher the intelligence the slower the decrease (for hunger: slower increase)
- [x] Intelligence can be improved by playing mini-games (for each play: intelligence + 1), up to a value of 100. Once it reaches 100 it will stay at that value.
- [x] The characteristics have the following updated effects:

   - [x] Smart: Pets start with a higher intelligence value, but health decreases 1.2x faster.
   - [x] Foolish: Pets start with a lower intelligence value, but health decreases slower (x0.8).
   - [x] Hyperactive: Pets move faster (visual effect) and snake/catch the food games speed increases.
   - [x] Lethargic: Pets move slower (visual effect) and snake/catch the food games speed decreases.
   - [x] Gluttonous: Hunger increases 1.2x faster, but energy depletes slower (x0.8).
   - [x] Temperate: Hunger increases slower (0.8x), but energy depletes 1.2x faster.
   - [x] Cheerful: Happiness decreases slower (0.8x), but intelligence gain after mini-games is reduced (0.8x).
   - [x] Melancholy: Happiness decreases 1.2x faster, but intelligence gain after mini-games is boosted (2x).

Tasks

- [x] Develop logic for dynamically calculating initial intelligence, happiness, hunger, and other relevant factors based on the selected characteristics.
- [x] Implement real-time updates for pet stats, ensuring that changes to characteristics are reflected immediately during gameplay and visible to the user.
- [x] implement intelligence logic

**Comment by ahohnsen** [comment]
I have a question:

How much can I increase the intelligence by playing mini-games? Up to 100? And what happens when I reach that value? Can I increase it beyond that? Does the intelligence stay at the maximum permanently, or does it decrease again over time?

**Comment by LorenzCoachK** [comment]
## Its amazing! The gamelogic is brilliant!

**Comment by Inelukas** [comment]
The intelligence will rise up to 100 and stay there once it reaches that value. I've already updated the US to include this information.
