### ISSUE TITLE
Game Refactoring

### ISSUE THREAD

**Issue by Inelukas** [Inelukas/pet-app#49]
Developer Story

Value Proposition
As a developer,
I want to refactor the code of the app's three mini-games
In order to make the codebase more unified, maintainable, and clean.

Description
The existing code for the three mini-games will be restructured for improved readability, maintainability, and performance. The refactoring process will focus on eliminating redundancy, improving the logic flow, and consolidating similar functionalities across the games.

Acceptance Criteria
- [ ] Redundant or duplicate states and logic across the three games are combined or abstracted where possible.
- [ ] Unnecessary or dead code is identified and removed.
- [ ] Game mechanics or logic that are shared between games are refactored into reusable functions or components.
- [ ] All three games function exactly as they did before the refactor with no new bugs introduced.

Tasks
- [ ] Create utility functions or reusable components to handle common logic across the games (e.g., input handling, score calculation).
- [ ] Refactor state transitions to be more consistent and concise.
- [ ] Identify and remove any dead code that is no longer relevant.
- [ ] Ensure that the removal of any code does not impact current functionality.

**Comment by Serco627** [comment]
it looks solid overall!! 👍 The focus on refactoring the code for the mini-games to improve readability, maintainability, and performance is clear and valuable.
